resources:
  containers:
    - container: tarpaulin
      image: xd009642/tarpaulin:latest-nightly
      options: --security-opt seccomp=unconfined

jobs:
  - job: LinuxOpenBLAS
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: |
          sudo apt-get update
          sudo apt-get install -y gfortran
        displayName: apt install
      - script: |
          cargo test -v --features=openblas --no-default-features
          cargo test -v --features=openblas,serde-1 --no-default-features
        displayName: run test

  - job: LinuxStaticOpenBLAS
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: |
          sudo apt-get update
          sudo apt-get install -y gfortran
        displayName: apt install
      - script: |
          cargo test -v --features=openblas-static --no-default-features
          cargo test -v --features=openblas-static,serde-1 --no-default-features
        displayName: run test

  - job: LinuxNetlib
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: |
          sudo apt-get update
          sudo apt-get install -y cmake gfortran
        displayName: apt install
      - script: |
          cargo test -v --features=netlib --no-default-features
          cargo test -v --features=netlib,serde-1 --no-default-features
        displayName: run test

  - job: LinuxIntelMKL
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: |
          cargo test -v --features=intel-mkl --no-default-features
          cargo test -v --features=intel-mkl,serde-1 --no-default-features
        displayName: run test

  - job: macOSIntelMKL
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: |
          cargo test -v --features=intel-mkl --no-default-features
          cargo test -v --features=intel-mkl,serde-1 --no-default-features
        displayName: run test

  - job: WindowsIntelMKL
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y 2>&1
          set PATH=%PATH%;%USERPROFILE%\.cargo\bin
          echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        displayName: install rustup on Windows
      - script: cargo test -v --features=intel-mkl --no-default-features 2>&1
        displayName: run test

  - job: Coverage
    pool:
      vmImage: 'ubuntu-16.04'
    container: tarpaulin
    steps:
      - script: |
          apt-get update
          apt-get install -y gfortran
        displayName: apt install
      - script: |
          cargo tarpaulin -v --features=openblas-static --out Xml
          curl -s https://codecov.io/bash -o .codecov && chmod +x .codecov
          ./.codecov -B "${BUILD_SOURCEBRANCHNAME:-}" \
                     -C "${BUILD_SOURCEVERSION:-}" \
                     -P "${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER:-}" \
                     -b "${BUILD_BUILDID:-}" \
                     -K -n "report name"
        displayName: 'run tarpaulin'
        env:
          CODECOV_TOKEN: $(myCodecovToken)
