jobs:
  - job: LinuxOpenBLAS
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y gfortran
        displayName: apt install gfortran
      - script: |
          cargo test -v --features=openblas --no-default-features
          cargo test -v --features=openblas,serde-1 --no-default-features
        displayName: run test

  - job: LinuxStaticOpenBLAS
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y gfortran
        displayName: apt install gfortran
      - script: |
          cargo test -v --features=openblas-static --no-default-features
          cargo test -v --features=openblas-static,serde-1 --no-default-features
        displayName: run test

  - job: LinuxNetlib
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y gfortran
        displayName: apt install gfortran
      - script: |
          cargo test -v --features=netlib --no-default-features
          cargo test -v --features=netlib,serde-1 --no-default-features
        displayName: run test

  - job: LinuxIntelMKL
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: |
          cargo test -v --features=intel-mkl --no-default-features
          cargo test -v --features=intel-mkl,serde-1 --no-default-features
        displayName: run test

  - job: macOSIntelMKL
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - script: |
          cargo test -v --features=intel-mkl --no-default-features
          cargo test -v --features=intel-mkl,serde-1 --no-default-features
        displayName: run test

  - job: WindowsIntelMKL
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: cargo test -v --features=intel-mkl --no-default-features 2>&1
        displayName: run test
