[package]
name    = "ndarray-linalg"
version = "0.8.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description   = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository    = "https://github.com/termoshtt/ndarray-linalg"
keywords      = ["ndarray", "lapack", "matrix"]
license       = "MIT"
readme        = "README.md"
categories    = ["algorithms", "science"]

[features]
default    = []
accelerate = ["lapack-src/accelerate"]
openblas   = ["lapack-src/openblas", "openblas-src"]
netlib     = ["lapack-src/netlib", "netlib-src"]
intel-mkl  = ["intel-mkl-src"]

[dependencies]
rand = "0.4"
derive-new = "0.5"
procedurals = "0.2"
num-traits  = "0.1"
num-complex = { version = "0.1", default-features = false }
ndarray = { version = "0.11", default-features = false }
lapacke = "0.1.4"
lapack-src = { version = "0.1", default-features = false }

[dependencies.intel-mkl-src]
version = "0.2"
default-features = false
optional = true

[dependencies.netlib-src]
version = "0.7.0"
features = ["static", "cblas", "lapacke", "tmg"]
default-features = false
optional = true

[dependencies.openblas-src]
version = "0.5.3"
features = ["static", "cblas", "lapacke"]
default-features = false
optional = true
