[package]
name = "ndarray-linalg"
version = "0.1.5"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository = "https://github.com/termoshtt/ndarray-linalg"
keywords = ["ndarray", "lapack", "matrix"]
license = "MIT"

[dependencies]
lapack = "0.11.1"
num-traits = "0.1.36"

[dependencies.ndarray]
version = "0.7"
features = ["blas"]

[dev-dependencies]
rand = "0.3.14"
ndarray-rand = "0.3"
float-cmp = "0.2.3"
