[package]
name = "ndarray-linalg"
version = "0.2.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository = "https://github.com/termoshtt/ndarray-linalg"
keywords = ["ndarray", "lapack", "matrix"]
license = "MIT"

[dependencies]
lapack = "0.11"
blas = "0.15"
num-traits = "0.1.36"

[dependencies.ndarray]
version = "0.7.3"
features = ["blas"]

[dev-dependencies]
ndarray-rand = "0.3"
ndarray-numtest = "0.1.4"
