[package]
name = "ndarray-linalg"
version = "0.1.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository = "https://github.com/termoshtt/ndarray-linalg"
keywords = ["ndarray", "lapack", "matrix"]
license = "MIT"

[dependencies]
lapack = "^0.11"
num-traits = "^0.1"

[dependencies.ndarray]
version = "^0.6.8"
features = ["blas"]

[dev-dependencies]
rand = "^0.3"
ndarray-rand = "^0.2"

