[package]
name    = "ndarray-linalg"
version = "0.8.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description   = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository    = "https://github.com/termoshtt/ndarray-linalg"
keywords      = ["ndarray", "lapack", "matrix"]
license       = "MIT"
readme        = "README.md"
categories    = ["algorithms", "science"]

[dependencies]
rand = "0.3"
derive-new = "0.5"
procedurals = "0.2"
num-traits  = "0.1"
num-complex = { version = "0.1", default-features = false }
lapacke = "0.1.4"

intel-mkl-src = { version = "0.2", optional = true }
openblas-src = { version = "*", optional = true }
netlib-src = { version = "*", optional = true }

[dependencies.ndarray]
version = "0.10"
default-features = false

[features]
default   = []
openblas  = ["openblas-src"]
netlib    = ["netlib-src"]
intel-mkl = ["intel-mkl-src"]
