[package]
name    = "ndarray-linalg"
version = "0.4.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description   = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository    = "https://github.com/termoshtt/ndarray-linalg"
keywords      = ["ndarray", "lapack", "matrix"]
license       = "MIT"

[features]
default  = ["openblas"]
openblas = ["blas/openblas", "lapack/openblas"]
netlib   = ["blas/netlib", "lapack/netlib"]

[dependencies]
float-cmp = "0.2"
num-traits = "0.1"
num-complex = "0.1"
ndarray = { version = "0.9",  default-features = false, features = ["blas"] }
lapack  = { version = "0.11", default-features = false }
blas    = { version = "0.15", default-features = false }

[dev-dependencies]
ndarray-rand    = "0.5"
rand-extra = { git = "http://github.com/termoshtt/rust-rand-extra" }
