array_layout = "Block"
array_width = 60
chain_indent = "Block"
chain_one_line_max = 60
chain_split_single_child = false
closure_block_indent_threshold = 7
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
control_style = "Rfc"
disable_all_formatting = false
error_on_line_overflow = true
fn_args_density = "Tall"
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_brace_style = "SameLineWhere"
fn_call_style = "Block"
fn_call_width = 60
fn_empty_single_line = true
fn_return_indent = "WithArgs"
fn_single_line = false
force_explicit_abi = true
force_format_strings = false
format_strings = false
generics_indent = "Block"
hard_tabs = false
impl_empty_single_line = true
indent_match_arms = true
item_brace_style = "SameLineWhere"
match_block_trailing_comma = false
max_width = 120
newline_style = "Unix"
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
report_fixme = "Never"
report_todo = "Never"
single_line_if_else_max_width = 50
skip_children = false
space_after_bound_colon = true
space_after_struct_lit_field_colon = true
space_after_type_annotation_colon = true
space_before_bound = false
space_before_struct_lit_field_colon = false
space_before_type_annotation = false
spaces_around_ranges = false
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false
struct_lit_multiline_style = "PreferSingle"
struct_lit_style = "Block"
struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 4
take_source_hints = false
trailing_comma = "Vertical"
type_punctuation_density = "Wide"
use_try_shorthand = true
verbose = false
where_density = "CompressedIfEmpty"
where_layout = "Vertical"
where_pred_indent = "Visual"
where_style = "Rfc"
wrap_comments = false
wrap_match_arms = true
write_mode = "Replace"
