[package]
name = "lax"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[features]
default    = []
intel-mkl  = ["lapack-src/intel-mkl", "blas-src/intel-mkl"]
netlib     = ["lapack-src/netlib", "blas-src/netlib"]
openblas   = ["lapack-src/openblas", "blas-src/openblas"]

[dependencies]
thiserror = "1.0"
cauchy = "0.2.0"
num-traits = "0.2"
lapack = "0.16.0"

[dependencies.blas-src]
version = "0.6.1"
default-features = false

[dependencies.lapack-src]
version = "0.6.0"
default-features = false

[dependencies.openblas-src]
version = "0.9.0"
default-features = false
features = ["static"]
optional = true
