[package]
name = "lax"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[features]
default = []

netlib    = ["netlib-static"]
openblas  = ["openblas-static"]
intel-mkl = ["mkl-static-lp64-seq"]

netlib-static = ["netlib-src/static"]
netlib-system = ["netlib-src/system"]
openblas-static = ["openblas-src/static"]
openblas-system = ["openblas-src/system"]

mkl-static-lp64-iomp   = ["intel-mkl-src/mkl-static-lp64-iomp"]
mkl-static-lp64-seq    = ["intel-mkl-src/mkl-static-lp64-seq"]
mkl-dynamic-lp64-iomp  = ["intel-mkl-src/mkl-dynamic-lp64-iomp"]
mkl-dynamic-lp64-seq   = ["intel-mkl-src/mkl-dynamic-lp64-seq"]

[dependencies]
thiserror = "1.0"
cauchy = "0.2.0"
num-traits = "0.2"
lapack = "0.16.0"

openblas-src  = { version = "0.9.0", optional = true }
netlib-src    = { version = "0.8.0", optional = true }
intel-mkl-src = { version = "0.6.0", default-features = false, features = ["download"], optional = true }
