version: 2.0

references:
  rust_cfg: &rust_cfg
    docker:
      - image: rust:1.26

jobs:
  test-openblas:
    <<: *rust_cfg
    steps:
      - checkout
      - run:
          name: test OpenBLAS backend
          command: cargo test --no-default-features --features=openblas

  test-netlib:
    <<: *rust_cfg
    steps:
      - checkout
      - run:
          name: test NetLib backend
          command: cargo test --no-default-features --features=netlib

  test-intel-mkl:
    <<: *rust_cfg
    steps:
      - checkout
      - run:
          name: test Intel MKL backend
          command: cargo test --no-default-features --features=intel-mkl

workflows:
  version: 2
  tests:
    jobs:
      - test-openblas
      - test-netlib
      - test-intel-mkl
