name: ndarray-linalg

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=ndarray-linalg/Cargo.toml --features=intel-mkl --no-default-features

  macos:
    runs-on: macos-10.15
    env:
      CC: gcc-9
      FC: gfortran-9
      LIBRARY_PATH: /usr/local/opt/gcc/lib/gcc/9
    strategy:
      fail-fast: false
      matrix:
        feature:
          - netlib
          - openblas
          - intel-mkl
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=ndarray-linalg/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          - netlib
          - openblas
          - intel-mkl
    steps:
    - uses: actions/checkout@v1
    - name: apt-install gfortran
      run: |
        sudo apt update
        sudo apt install -y gfortran
      if: ${{ matrix.feature != 'intel-mkl' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=ndarray-linalg/Cargo.toml --features=${{ matrix.feature }} --no-default-features
